;; pindolfo2scm v1.2
(define (LEAF0 v-code) (let* ((a-0 (DISPATCH12 v-code))) a-0))
(define (LEAF1 v-actions v-pattern)
  (let* ((a-0 (DISPATCH11 v-actions v-pattern))) a-0))
(define (LEAF2 v-actions v-pattern)
  (let* ((a-0 (DISPATCH10 v-actions))) (cons v-pattern (cons a-0 '()))))
(define (LEAF3 v-bnd v-todo v-exp v-var)
  (let* ((a-0 (DISPATCH9 v-exp v-bnd))
         (a-1 (DISPATCH8 v-var a-0 v-bnd v-todo)))
    a-1))
(define (LEAF4 v-bnd v-exp) (let* ((a-0 (DISPATCH9 v-exp v-bnd))) a-0))
(define (LEAF5 v-sym v-bnd) (let* ((a-0 (DISPATCH7 v-bnd v-sym))) a-0))
(define (LEAF6 v-e v-bnd)
  (let* ((a-0 (DISPATCH6 v-e v-bnd))) (cons 'quasiquote (cons a-0 '()))))
(define (LEAF7 v-e v-bnd)
  (let* ((a-0 (DISPATCH6 v-e v-bnd))) (cons 'rec (cons a-0 '()))))
(define (LEAF8 v-e v-bnd) v-e)
(define (LEAF9 v-e v-bnd)
  (let* ((a-0 (DISPATCH5 v-e v-bnd))) (cons 'unquote (cons a-0 '()))))
(define (LEAF10 v-t v-h v-bnd)
  (let* ((a-0 (DISPATCH4 v-h v-bnd)) (a-1 (DISPATCH3 v-t v-bnd)))
    (cons a-0 a-1)))
(define (LEAF11 v-e v-bnd) v-e)
(define (LEAF12 v-proc) '())
(define (LEAF13 v-xs v-x v-proc)
  (let* ((a-0 (DISPATCH2 v-x v-proc)) (a-1 (DISPATCH1 v-xs v-proc)))
    (cons a-0 a-1)))
(define (LEAF14 v-sym) v-sym)
(define (LEAF15 v-val v-sym) v-val)
(define (LEAF16 v-bnd v-sym) (let* ((a-0 (DISPATCH7 v-bnd v-sym))) a-0))
(define (DISPATCH0 v0)
  (if (pair? v0)
      (if (equal? 'unLETized (car v0))
          (if (pair? (cdr v0))
              (if (null? (cdr (cdr v0))) (LEAF0 (car (cdr v0))) (FAIL v0))
              (FAIL v0))
          (if (equal? 'unLET (car v0))
              (if (pair? (cdr v0))
                  (if (pair? (car (cdr v0)))
                      (if (pair? (cdr (car (cdr v0))))
                          (if (equal? '=> (car (cdr (car (cdr v0)))))
                              (if (null? (cdr (cdr v0)))
                                  (LEAF1 (cdr (cdr (car (cdr v0))))
                                         (car (car (cdr v0))))
                                  (FAIL v0))
                              (if (null? (cdr (cdr v0)))
                                  (LEAF2 (cdr (car (cdr v0)))
                                         (car (car (cdr v0))))
                                  (FAIL v0)))
                          (if (null? (cdr (cdr v0)))
                              (LEAF2 (cdr (car (cdr v0))) (car (car (cdr v0))))
                              (FAIL v0)))
                      (FAIL v0))
                  (FAIL v0))
              (if (equal? 'unLETact (car v0))
                  (if (pair? (cdr v0))
                      (if (pair? (car (cdr v0)))
                          (if (symbol? (car (car (cdr v0))))
                              (if (pair? (cdr (car (cdr v0))))
                                  (if (equal? '<- (car (cdr (car (cdr v0)))))
                                      (if (pair? (cdr (cdr (car (cdr v0)))))
                                          (if (pair? (cdr (cdr v0)))
                                              (if (null? (cdr (cdr (cdr v0))))
                                                  (LEAF3 (car (cdr (cdr v0)))
                                                         (cdr (cdr (cdr (car (cdr v0)))))
                                                         (car (cdr (cdr (car (cdr v0)))))
                                                         (car (car (cdr v0))))
                                                  (FAIL v0))
                                              (FAIL v0))
                                          (FAIL v0))
                                      (FAIL v0))
                                  (if (null? (cdr (car (cdr v0))))
                                      (if (pair? (cdr (cdr v0)))
                                          (if (null? (cdr (cdr (cdr v0))))
                                              (LEAF4 (car (cdr (cdr v0)))
                                                     (car (car (cdr v0))))
                                              (FAIL v0))
                                          (FAIL v0))
                                      (FAIL v0)))
                              (if (null? (cdr (car (cdr v0))))
                                  (if (pair? (cdr (cdr v0)))
                                      (if (null? (cdr (cdr (cdr v0))))
                                          (LEAF4 (car (cdr (cdr v0)))
                                                 (car (car (cdr v0))))
                                          (FAIL v0))
                                      (FAIL v0))
                                  (FAIL v0)))
                          (FAIL v0))
                      (FAIL v0))
                  (if (equal? 'SUB (car v0))
                      (if (pair? (cdr v0))
                          (if (pair? (cdr (cdr v0)))
                              (if (equal? 'in (car (cdr (cdr v0))))
                                  (if (pair? (cdr (cdr (cdr v0))))
                                      (if (symbol? (car (cdr (cdr (cdr v0)))))
                                          (if (null? (cdr (cdr (cdr (cdr v0)))))
                                              (LEAF5 (car (cdr (cdr (cdr v0))))
                                                     (car (cdr v0)))
                                              (FAIL v0))
                                          (if (pair? (car (cdr (cdr (cdr v0)))))
                                              (if (equal?
                                                   'quasiquote
                                                   (car (car (cdr (cdr (cdr v0))))))
                                                  (if (pair? (cdr (car (cdr (cdr (cdr v0))))))
                                                      (if (null? (cdr (cdr (car (cdr (cdr (cdr v0)))))))
                                                          (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                              (LEAF6 (car (cdr (car (cdr (cdr (cdr v0))))))
                                                                     (car (cdr v0)))
                                                              (FAIL v0))
                                                          (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                              (LEAF8 (car (cdr (cdr (cdr v0))))
                                                                     (car (cdr v0)))
                                                              (FAIL v0)))
                                                      (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                          (LEAF8 (car (cdr (cdr (cdr v0))))
                                                                 (car (cdr v0)))
                                                          (FAIL v0)))
                                                  (if (equal?
                                                       'rec
                                                       (car (car (cdr (cdr (cdr v0))))))
                                                      (if (pair? (cdr (car (cdr (cdr (cdr v0))))))
                                                          (if (null? (cdr (cdr (car (cdr (cdr (cdr v0)))))))
                                                              (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                                  (LEAF7 (car (cdr (car (cdr (cdr (cdr v0))))))
                                                                         (car (cdr v0)))
                                                                  (FAIL v0))
                                                              (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                                  (LEAF8 (car (cdr (cdr (cdr v0))))
                                                                         (car (cdr v0)))
                                                                  (FAIL v0)))
                                                          (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                              (LEAF8 (car (cdr (cdr (cdr v0))))
                                                                     (car (cdr v0)))
                                                              (FAIL v0)))
                                                      (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                          (LEAF8 (car (cdr (cdr (cdr v0))))
                                                                 (car (cdr v0)))
                                                          (FAIL v0))))
                                              (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                  (LEAF8 (car (cdr (cdr (cdr v0))))
                                                         (car (cdr v0)))
                                                  (FAIL v0))))
                                      (FAIL v0))
                                  (FAIL v0))
                              (FAIL v0))
                          (FAIL v0))
                      (if (equal? 'SUB-qq (car v0))
                          (if (pair? (cdr v0))
                              (if (pair? (cdr (cdr v0)))
                                  (if (equal? 'in (car (cdr (cdr v0))))
                                      (if (pair? (cdr (cdr (cdr v0))))
                                          (if (pair? (car (cdr (cdr (cdr v0)))))
                                              (if (equal?
                                                   'unquote
                                                   (car (car (cdr (cdr (cdr v0))))))
                                                  (if (pair? (cdr (car (cdr (cdr (cdr v0))))))
                                                      (if (null? (cdr (cdr (car (cdr (cdr (cdr v0)))))))
                                                          (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                              (LEAF9 (car (cdr (car (cdr (cdr (cdr v0))))))
                                                                     (car (cdr v0)))
                                                              (FAIL v0))
                                                          (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                              (LEAF10
                                                               (cdr (car (cdr (cdr (cdr v0)))))
                                                               (car (car (cdr (cdr (cdr v0)))))
                                                               (car (cdr v0)))
                                                              (FAIL v0)))
                                                      (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                          (LEAF10
                                                           (cdr (car (cdr (cdr (cdr v0)))))
                                                           (car (car (cdr (cdr (cdr v0)))))
                                                           (car (cdr v0)))
                                                          (FAIL v0)))
                                                  (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                      (LEAF10
                                                       (cdr (car (cdr (cdr (cdr v0)))))
                                                       (car (car (cdr (cdr (cdr v0)))))
                                                       (car (cdr v0)))
                                                      (FAIL v0)))
                                              (if (null? (cdr (cdr (cdr (cdr v0)))))
                                                  (LEAF11
                                                   (car (cdr (cdr (cdr v0))))
                                                   (car (cdr v0)))
                                                  (FAIL v0)))
                                          (FAIL v0))
                                      (FAIL v0))
                                  (FAIL v0))
                              (FAIL v0))
                          (if (equal? 'map (car v0))
                              (if (pair? (cdr v0))
                                  (if (pair? (cdr (cdr v0)))
                                      (if (null? (car (cdr (cdr v0))))
                                          (if (null? (cdr (cdr (cdr v0))))
                                              (LEAF12 (car (cdr v0)))
                                              (FAIL v0))
                                          (if (pair? (car (cdr (cdr v0))))
                                              (if (null? (cdr (cdr (cdr v0))))
                                                  (LEAF13
                                                   (cdr (car (cdr (cdr v0))))
                                                   (car (car (cdr (cdr v0))))
                                                   (car (cdr v0)))
                                                  (FAIL v0))
                                              (FAIL v0)))
                                      (FAIL v0))
                                  (FAIL v0))
                              (if (equal? 'LU/id (car v0))
                                  (if (pair? (cdr v0))
                                      (if (symbol? (car (cdr v0)))
                                          (if (pair? (cdr (cdr v0)))
                                              (if (null? (car (cdr (cdr v0))))
                                                  (if (null? (cdr (cdr (cdr v0))))
                                                      (LEAF14 (car (cdr v0)))
                                                      (FAIL v0))
                                                  (if (pair? (car (cdr (cdr v0))))
                                                      (if (pair? (car (car (cdr (cdr v0)))))
                                                          (if (equal?
                                                               (car (cdr v0))
                                                               (car (car (car (cdr (cdr v0))))))
                                                              (if (pair? (cdr (car (car (cdr (cdr v0))))))
                                                                  (if (null? (cdr (cdr (car (car (cdr (cdr v0)))))))
                                                                      (if (null? (cdr (cdr (cdr v0))))
                                                                          (LEAF15
                                                                           (car (cdr (car (car (cdr (cdr v0))))))
                                                                           (car (cdr v0)))
                                                                          (FAIL v0))
                                                                      (if (null? (cdr (cdr (cdr v0))))
                                                                          (LEAF16
                                                                           (cdr (car (cdr (cdr v0))))
                                                                           (car (cdr v0)))
                                                                          (FAIL v0)))
                                                                  (if (null? (cdr (cdr (cdr v0))))
                                                                      (LEAF16
                                                                       (cdr (car (cdr (cdr v0))))
                                                                       (car (cdr v0)))
                                                                      (FAIL v0)))
                                                              (if (null? (cdr (cdr (cdr v0))))
                                                                  (LEAF16
                                                                   (cdr (car (cdr (cdr v0))))
                                                                   (car (cdr v0)))
                                                                  (FAIL v0)))
                                                          (if (null? (cdr (cdr (cdr v0))))
                                                              (LEAF16
                                                               (cdr (car (cdr (cdr v0))))
                                                               (car (cdr v0)))
                                                              (FAIL v0)))
                                                      (FAIL v0)))
                                              (FAIL v0))
                                          (FAIL v0))
                                      (FAIL v0))
                                  (FAIL v0))))))))
      (FAIL v0)))
(define (DISPATCH1 v-xs v-proc)
  (if (null? v-xs)
      (LEAF12 v-proc)
      (if (pair? v-xs)
          (LEAF13 (cdr v-xs) (car v-xs) v-proc)
          (FAIL (cons 'map (cons v-proc (cons v-xs '())))))))
(define (DISPATCH2 v-x v-proc)
  (if (equal? 'unLETized v-proc)
      (LEAF0 v-x)
      (if (equal? 'unLET v-proc)
          (if (pair? v-x)
              (if (pair? (cdr v-x))
                  (if (equal? '=> (car (cdr v-x)))
                      (LEAF1 (cdr (cdr v-x)) (car v-x))
                      (LEAF2 (cdr v-x) (car v-x)))
                  (LEAF2 (cdr v-x) (car v-x)))
              (FAIL (cons v-proc (cons v-x '()))))
          (if (equal? 'unLETact v-proc)
              (if (pair? v-x)
                  (if (symbol? (car v-x))
                      (if (pair? (cdr v-x))
                          (if (equal? '<- (car (cdr v-x)))
                              (if (pair? (cdr (cdr v-x)))
                                  (FAIL (cons v-proc (cons v-x '())))
                                  (FAIL (cons v-proc (cons v-x '()))))
                              (FAIL (cons v-proc (cons v-x '()))))
                          (if (null? (cdr v-x))
                              (FAIL (cons v-proc (cons v-x '())))
                              (FAIL (cons v-proc (cons v-x '())))))
                      (if (null? (cdr v-x))
                          (FAIL (cons v-proc (cons v-x '())))
                          (FAIL (cons v-proc (cons v-x '())))))
                  (FAIL (cons v-proc (cons v-x '()))))
              (if (equal? 'SUB v-proc)
                  (FAIL (cons v-proc (cons v-x '())))
                  (if (equal? 'SUB-qq v-proc)
                      (FAIL (cons v-proc (cons v-x '())))
                      (if (equal? 'map v-proc)
                          (FAIL (cons v-proc (cons v-x '())))
                          (if (equal? 'LU/id v-proc)
                              (if (symbol? v-x)
                                  (FAIL (cons v-proc (cons v-x '())))
                                  (FAIL (cons v-proc (cons v-x '()))))
                              (FAIL (cons v-proc (cons v-x '())))))))))))
(define (DISPATCH3 v-t v-bnd)
  (if (pair? v-t)
      (if (equal? 'unquote (car v-t))
          (if (pair? (cdr v-t))
              (if (null? (cdr (cdr v-t)))
                  (LEAF9 (car (cdr v-t)) v-bnd)
                  (LEAF10 (cdr v-t) (car v-t) v-bnd))
              (LEAF10 (cdr v-t) (car v-t) v-bnd))
          (LEAF10 (cdr v-t) (car v-t) v-bnd))
      (LEAF11 v-t v-bnd)))
(define (DISPATCH4 v-h v-bnd)
  (if (pair? v-h)
      (if (equal? 'unquote (car v-h))
          (if (pair? (cdr v-h))
              (if (null? (cdr (cdr v-h)))
                  (LEAF9 (car (cdr v-h)) v-bnd)
                  (LEAF10 (cdr v-h) (car v-h) v-bnd))
              (LEAF10 (cdr v-h) (car v-h) v-bnd))
          (LEAF10 (cdr v-h) (car v-h) v-bnd))
      (LEAF11 v-h v-bnd)))
(define (DISPATCH5 v-e v-bnd)
  (if (symbol? v-e)
      (LEAF5 v-e v-bnd)
      (if (pair? v-e)
          (if (equal? 'quasiquote (car v-e))
              (if (pair? (cdr v-e))
                  (if (null? (cdr (cdr v-e)))
                      (LEAF6 (car (cdr v-e)) v-bnd)
                      (LEAF8 v-e v-bnd))
                  (LEAF8 v-e v-bnd))
              (if (equal? 'rec (car v-e))
                  (if (pair? (cdr v-e))
                      (if (null? (cdr (cdr v-e)))
                          (LEAF7 (car (cdr v-e)) v-bnd)
                          (LEAF8 v-e v-bnd))
                      (LEAF8 v-e v-bnd))
                  (LEAF8 v-e v-bnd)))
          (LEAF8 v-e v-bnd))))
(define (DISPATCH6 v-e v-bnd)
  (if (pair? v-e)
      (if (equal? 'unquote (car v-e))
          (if (pair? (cdr v-e))
              (if (null? (cdr (cdr v-e)))
                  (LEAF9 (car (cdr v-e)) v-bnd)
                  (LEAF10 (cdr v-e) (car v-e) v-bnd))
              (LEAF10 (cdr v-e) (car v-e) v-bnd))
          (LEAF10 (cdr v-e) (car v-e) v-bnd))
      (LEAF11 v-e v-bnd)))
(define (DISPATCH7 v-bnd v-sym)
  (if (symbol? v-sym)
      (if (null? v-bnd)
          (LEAF14 v-sym)
          (if (pair? v-bnd)
              (if (pair? (car v-bnd))
                  (if (equal? v-sym (car (car v-bnd)))
                      (if (pair? (cdr (car v-bnd)))
                          (if (null? (cdr (cdr (car v-bnd))))
                              (LEAF15 (car (cdr (car v-bnd))) v-sym)
                              (LEAF16 (cdr v-bnd) v-sym))
                          (LEAF16 (cdr v-bnd) v-sym))
                      (LEAF16 (cdr v-bnd) v-sym))
                  (LEAF16 (cdr v-bnd) v-sym))
              (FAIL (cons 'LU/id (cons v-sym (cons v-bnd '()))))))
      (FAIL (cons 'LU/id (cons v-sym (cons v-bnd '()))))))
(define (DISPATCH8 v-var a-0 v-bnd v-todo)
  (if (pair? v-todo)
      (if (symbol? (car v-todo))
          (if (pair? (cdr v-todo))
              (if (equal? '<- (car (cdr v-todo)))
                  (if (pair? (cdr (cdr v-todo)))
                      (LEAF3 (cons (cons v-var (cons a-0 '())) v-bnd)
                             (cdr (cdr (cdr v-todo)))
                             (car (cdr (cdr v-todo)))
                             (car v-todo))
                      (FAIL (cons 'unLETact
                                  (cons v-todo
                                        (cons (cons (cons v-var (cons a-0 '()))
                                                    v-bnd)
                                              '())))))
                  (FAIL (cons 'unLETact
                              (cons v-todo
                                    (cons (cons (cons v-var (cons a-0 '()))
                                                v-bnd)
                                          '())))))
              (if (null? (cdr v-todo))
                  (LEAF4 (cons (cons v-var (cons a-0 '())) v-bnd) (car v-todo))
                  (FAIL (cons 'unLETact
                              (cons v-todo
                                    (cons (cons (cons v-var (cons a-0 '()))
                                                v-bnd)
                                          '()))))))
          (if (null? (cdr v-todo))
              (LEAF4 (cons (cons v-var (cons a-0 '())) v-bnd) (car v-todo))
              (FAIL (cons 'unLETact
                          (cons v-todo
                                (cons (cons (cons v-var (cons a-0 '())) v-bnd)
                                      '()))))))
      (FAIL (cons 'unLETact
                  (cons v-todo
                        (cons (cons (cons v-var (cons a-0 '())) v-bnd) '()))))))
(define (DISPATCH9 v-exp v-bnd)
  (if (symbol? v-exp)
      (LEAF5 v-exp v-bnd)
      (if (pair? v-exp)
          (if (equal? 'quasiquote (car v-exp))
              (if (pair? (cdr v-exp))
                  (if (null? (cdr (cdr v-exp)))
                      (LEAF6 (car (cdr v-exp)) v-bnd)
                      (LEAF8 v-exp v-bnd))
                  (LEAF8 v-exp v-bnd))
              (if (equal? 'rec (car v-exp))
                  (if (pair? (cdr v-exp))
                      (if (null? (cdr (cdr v-exp)))
                          (LEAF7 (car (cdr v-exp)) v-bnd)
                          (LEAF8 v-exp v-bnd))
                      (LEAF8 v-exp v-bnd))
                  (LEAF8 v-exp v-bnd)))
          (LEAF8 v-exp v-bnd))))
(define (DISPATCH10 v-actions)
  (if (pair? v-actions)
      (if (symbol? (car v-actions))
          (if (pair? (cdr v-actions))
              (if (equal? '<- (car (cdr v-actions)))
                  (if (pair? (cdr (cdr v-actions)))
                      (LEAF3 '()
                             (cdr (cdr (cdr v-actions)))
                             (car (cdr (cdr v-actions)))
                             (car v-actions))
                      (FAIL (cons 'unLETact (cons v-actions (cons '() '())))))
                  (FAIL (cons 'unLETact (cons v-actions (cons '() '())))))
              (if (null? (cdr v-actions))
                  (LEAF4 '() (car v-actions))
                  (FAIL (cons 'unLETact (cons v-actions (cons '() '()))))))
          (if (null? (cdr v-actions))
              (LEAF4 '() (car v-actions))
              (FAIL (cons 'unLETact (cons v-actions (cons '() '()))))))
      (FAIL (cons 'unLETact (cons v-actions (cons '() '()))))))
(define (DISPATCH11 v-actions v-pattern)
  (if (pair? v-actions)
      (if (equal? '=> (car v-actions))
          (LEAF1 (cdr v-actions) v-pattern)
          (LEAF2 v-actions v-pattern))
      (LEAF2 v-actions v-pattern)))
(define (DISPATCH12 v-code)
  (if (null? v-code)
      (LEAF12 'unLET)
      (if (pair? v-code)
          (LEAF13 (cdr v-code) (car v-code) 'unLET)
          (FAIL (cons 'map (cons 'unLET (cons v-code '())))))))
(define (FAIL a) (display `(NO MATCH FOUND FOR ,a)) (newline) (error "halt"))
(begin (write (DISPATCH0 (read))) (newline))

